import { JobApplication } from "@/types/job";

export const mockJobs: JobApplication[] = [
  {
    id: "1",
    company: "TechCorp Inc",
    companyUrl: "https://techcorp.example.com",
    position: "Senior Software Engineer",
    status: "technical",
    appliedDate: "2026-01-15",
    location: "San Francisco, CA",
    jobType: "full-time",
    salary: "$150k - $180k",
    description: "Building scalable web applications with React and Node.js",
    url: "https://techcorp.example.com/jobs/senior-swe",
    contact: {
      name: "Sarah Johnson",
      role: "Senior Recruiter",
      email: "sarah.johnson@techcorp.com",
      phone: "(555) 123-4567",
    },
    interviewStages: [
      {
        id: "1-1",
        name: "Application Review",
        date: "2026-01-15",
        completed: true,
        notes: "Application submitted successfully",
      },
      {
        id: "1-2",
        name: "Recruiter Phone Screen",
        date: "2026-01-18",
        completed: true,
        notes: "30-minute call with Sarah from recruiting",
        feedback: "Great conversation, moving forward to technical round",
      },
      {
        id: "1-3",
        name: "Technical Interview",
        date: "2026-01-25",
        completed: false,
        notes: "90-minute coding interview with engineering team",
      },
      {
        id: "1-4",
        name: "Final Round",
        date: "2026-02-01",
        completed: false,
        notes: "Meet with hiring manager and team lead",
      },
    ],
    notes: "Really excited about this role. Team seems great and the tech stack aligns with my experience.",
  },
  {
    id: "2",
    company: "DataFlow Systems",
    position: "Full Stack Developer",
    status: "final_round",
    appliedDate: "2026-01-10",
    location: "Remote",
    jobType: "full-time",
    salary: "$140k - $170k",
    description: "Work on data visualization and analytics platforms",
    interviewStages: [
      {
        id: "2-1",
        name: "Application Review",
        date: "2026-01-10",
        completed: true,
      },
      {
        id: "2-2",
        name: "Phone Screen",
        date: "2026-01-14",
        completed: true,
        feedback: "Strong technical background",
      },
      {
        id: "2-3",
        name: "Technical Assessment",
        date: "2026-01-20",
        completed: true,
        notes: "Take-home project - built a data dashboard",
        feedback: "Excellent work on the project. Clean code and good UI/UX decisions.",
      },
      {
        id: "2-4",
        name: "Onsite Interviews",
        date: "2026-01-28",
        completed: true,
        notes: "Met with 4 team members throughout the day",
        feedback: "Team felt very positive about the interviews",
      },
      {
        id: "2-5",
        name: "Final Interview",
        date: "2026-02-03",
        completed: false,
        notes: "Meeting with VP of Engineering",
      },
    ],
  },
  {
    id: "3",
    company: "CloudNine",
    position: "Frontend Engineer",
    status: "phone_screen",
    appliedDate: "2026-01-20",
    location: "Austin, TX",
    jobType: "full-time",
    salary: "$130k - $160k",
    description: "Build modern web experiences with React and TypeScript",
    interviewStages: [
      {
        id: "3-1",
        name: "Application Review",
        date: "2026-01-20",
        completed: true,
      },
      {
        id: "3-2",
        name: "Recruiter Call",
        date: "2026-02-01",
        completed: false,
        notes: "Scheduled for next week",
      },
    ],
    notes: "Company culture looks amazing. Would love to relocate to Austin.",
  },
  {
    id: "4",
    company: "StartupXYZ",
    position: "Software Engineer",
    status: "applied",
    appliedDate: "2026-01-28",
    location: "New York, NY",
    jobType: "full-time",
    salary: "$120k - $150k",
    description: "Early-stage startup building fintech products",
    interviewStages: [
      {
        id: "4-1",
        name: "Application Submitted",
        date: "2026-01-28",
        completed: true,
      },
    ],
    notes: "Applied through a referral from Alex",
  },
  {
    id: "5",
    company: "Enterprise Solutions Ltd",
    position: "Lead Developer",
    status: "offer",
    appliedDate: "2026-01-05",
    location: "Seattle, WA",
    jobType: "full-time",
    salary: "$170k - $200k",
    description: "Lead a team of developers building enterprise software",
    interviewStages: [
      {
        id: "5-1",
        name: "Application Review",
        date: "2026-01-05",
        completed: true,
      },
      {
        id: "5-2",
        name: "Phone Screen",
        date: "2026-01-08",
        completed: true,
        feedback: "Strong leadership experience",
      },
      {
        id: "5-3",
        name: "Technical Interview",
        date: "2026-01-12",
        completed: true,
        feedback: "Excellent system design discussion",
      },
      {
        id: "5-4",
        name: "Final Round",
        date: "2026-01-19",
        completed: true,
        feedback: "Team loved the presentation",
      },
      {
        id: "5-5",
        name: "Offer Extended",
        date: "2026-01-26",
        completed: true,
        notes: "Received formal offer letter. Need to respond by Feb 9th",
      },
    ],
    notes: "Great offer! Considering along with other opportunities.",
  },
  {
    id: "6",
    company: "MegaCorp Global",
    position: "Senior Frontend Engineer",
    status: "rejected",
    appliedDate: "2026-01-08",
    location: "Boston, MA",
    jobType: "full-time",
    interviewStages: [
      {
        id: "6-1",
        name: "Application Review",
        date: "2026-01-08",
        completed: true,
      },
      {
        id: "6-2",
        name: "Phone Screen",
        date: "2026-01-12",
        completed: true,
      },
      {
        id: "6-3",
        name: "Technical Interview",
        date: "2026-01-16",
        completed: true,
        feedback: "Looking for someone with more React Native experience",
      },
    ],
    notes: "Not the right fit for their mobile-first approach. Good learning experience.",
  },
  {
    id: "7",
    company: "InnovateLabs",
    position: "Full Stack Engineer",
    status: "applied",
    appliedDate: "2026-01-29",
    location: "Remote",
    jobType: "full-time",
    salary: "$135k - $165k",
    description: "Building AI-powered developer tools",
    interviewStages: [
      {
        id: "7-1",
        name: "Application Submitted",
        date: "2026-01-29",
        completed: true,
      },
    ],
  },
  {
    id: "8",
    company: "FinTech Innovations",
    position: "Backend Engineer",
    status: "technical",
    appliedDate: "2026-01-12",
    location: "Chicago, IL",
    jobType: "full-time",
    salary: "$145k - $175k",
    interviewStages: [
      {
        id: "8-1",
        name: "Application Review",
        date: "2026-01-12",
        completed: true,
      },
      {
        id: "8-2",
        name: "Phone Screen",
        date: "2026-01-16",
        completed: true,
      },
      {
        id: "8-3",
        name: "System Design Interview",
        date: "2026-01-30",
        completed: false,
        notes: "Design a payment processing system",
      },
    ],
  },
];